//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsApi.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADS_FLASHED_UNITS
    {
        public decimal FLASH_ID { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public Nullable<decimal> SERIAL_NUMBER_ID { get; set; }
        public string CUSTOMER_NUMBER { get; set; }
        public Nullable<System.DateTime> FLASH_DATE { get; set; }
        public string VEHICLE_MAKE { get; set; }
        public string VEHICLE_MODEL { get; set; }
        public string VEHICLE_YEAR { get; set; }
        public string USER_FLASH_UNIT { get; set; }
        public Nullable<decimal> INVENTORY_ITEM_ID { get; set; }
        public string INV_FLAG { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
    }
}
