//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsApi.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADS_SERIAL_TRACKING
    {
        public string SERIAL_NUMBER { get; set; }
        public Nullable<decimal> SERIAL_NUMBER_ID { get; set; }
        public string SKU { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public Nullable<decimal> CUSTOMER_NUMBER { get; set; }
        public string SHIP_TO_ADDRESS1 { get; set; }
        public string SHIP_TO_ADDRESS2 { get; set; }
        public string SHIP_TO_ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public string STATE_PROVINCE { get; set; }
        public string POSTAL_CODE { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<System.DateTime> SHIP_DATE { get; set; }
        public Nullable<decimal> ORDER_NUMBER { get; set; }
        public Nullable<System.DateTime> ADS_PICK_DATE { get; set; }
        public Nullable<System.DateTime> ADS_FLASH_DATE { get; set; }
        public Nullable<decimal> FLASH_INVOICE_NUMBER { get; set; }
        public string ACK_MESSAGE { get; set; }
        public Nullable<System.DateTime> ACK_DATE { get; set; }
        public string ACK_CODE { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_EMAIL { get; set; }
        public decimal ID { get; set; }
        public Nullable<decimal> LOCATION_ID { get; set; }
    }
}
