//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsApi.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADS_DEALER_LOCATIONS
    {
        public long ID { get; set; }
        public string DEALER_NAME { get; set; }
        public long ASSOCIATED_CUSTOMER_ID { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public string ADDRESS_3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string POSTAL_CODE { get; set; }
        public string EMAIL { get; set; }
        public string URL { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string FACEBOOK_URL { get; set; }
        public string PREMIUM_DEALER { get; set; }
        public string ADS { get; set; }
    }
}
