//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsApi.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADS_ERROR_LOG
    {
        public decimal ERROR_ID { get; set; }
        public string REQUEST { get; set; }
        public string TYPE { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<System.DateTime> TIME_DATE { get; set; }
        public string SERIAL { get; set; }
    }
}
