//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsApi.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADS_UPGRADES
    {
        public decimal UPGRADE_ID { get; set; }
        public Nullable<decimal> FLASH_ID { get; set; }
        public string UPGRADE { get; set; }
    }
}
