//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsApi.Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AdsEntities : DbContext
    {
        public AdsEntities()
            : base("name=AdsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADS_UPGRADES> ADS_UPGRADES { get; set; }
        public virtual DbSet<ADS_FLASHED_UNITS> XXRF_ADS_FLASHED_UNITS { get; set; }
        public virtual DbSet<ADS_ERROR_LOG> XXRF_ADS_ERROR_LOG { get; set; }
        public virtual DbSet<ADS_SERIAL_TRACKING> XXRF_ADS_SERIAL_TRACKING { get; set; }
    
        public virtual ObjectResult<Nullable<float>> XXRF_ADS_GET_FLASH_ID(ObjectParameter p_FLASH_ID)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<float>>("XXRF_ADS_GET_FLASH_ID", p_FLASH_ID);
        }
    }
}
